---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    EntandoResourceKind: "EntandoPlugin"
    EntandoResourceNamespace: "my-namespace"
  name: "my-plugin-20537030"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "acc933d2-bfbf-4207-a2d9-9610bdcb9fae"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-14T13:17:43Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "9291478"
  uid: "acc933d2-bfbf-4207-a2d9-9610bdcb9fae"
lastTimestamp: "2021-06-14T13:17:43Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Test\
  \ Exception. Fix the root cause and then trigger a redeployment by adding the annotation\
  \ 'entando.org/processing-instruction: force'"
reason: "Failed"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
