---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    EntandoResourceKind: "EntandoPlugin"
    EntandoResourceNamespace: "my-namespace"
  name: "my-plugin-67699233"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "e7dcabf5-9fa1-47b9-8dc6-326142aafece"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-06T14:26:58Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "1650598"
  uid: "e7dcabf5-9fa1-47b9-8dc6-326142aafece"
lastTimestamp: "2021-07-06T14:26:58Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Fake\
  \ Controller Exception. Fix the root cause and then trigger a redeployment by adding\
  \ the annotation 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-zwbq9-15-from-build-pack-9-zg995"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
