---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "ProvidedCapability"
    ProvidedCapability: "my-keycloak"
    EntandoResourceNamespace: "my-namespace"
  name: "my-keycloak-87453275"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "ProvidedCapability"
    blockOwnerDeletion: true
    controller: true
    name: "my-keycloak"
    uid: "1e4bd984-38cb-434f-bcc9-5e4e732e685e"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-07T12:21:56Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "ProvidedCapability"
  fieldPath: "status"
  name: "my-keycloak"
  namespace: "my-namespace"
  resourceVersion: "5883138"
  uid: "1e4bd984-38cb-434f-bcc9-5e4e732e685e"
lastTimestamp: "2021-06-07T12:21:56Z"
message: "The deployment of ProvidedCapability my-namespace/my-keycloak failed due\
  \ to Could not prepare a database for SSO my-namespace/my-keycloak:\n. Fix the root\
  \ cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
source:
  component: "entando-k8s-d-capability-controller"
type: "Error"
