
Showing logs for build [32mentando-entando-engine-pr-143-p-vlc6x-3[0m stage [32mfrom-build-pack[0m and container [32mcredential-initializer[0m
{"level":"info","ts":1620973314.1672027,"caller":"creds-init/main.go:44","msg":"Credentials initialized."}

Showing logs for build [32mentando-entando-engine-pr-143-p-vlc6x-3[0m stage [32mfrom-build-pack[0m and container [32mworking-dir-initializer[0m

Showing logs for build [32mentando-entando-engine-pr-143-p-vlc6x-3[0m stage [32mfrom-build-pack[0m and container [32mplace-tools[0m

Showing logs for build [32mentando-entando-engine-pr-143-p-vlc6x-3[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-entando-entando-engine-pr-143-p-vlc6x-wjdzj[0m
{"level":"error","ts":1620973513.5078714,"caller":"git/git.go:41","msg":"Error running git [remote add origin https://github.com/entando/entando-engine.git]: exit status 128\nfatal: remote origin already exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:79\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1620973513.508409,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:203"}
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-git-source-entando-entando-engine-pr-143-p-vlc6x-wjdzj'. The execution of the pipeline has stopped.[0m
