---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "TestResource"
    EntandoResourceNamespace: "my-namespace"
    TestResource: "my-app"
  name: "my-app-46245249"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "test.org/v1"
    kind: "TestResource"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "3329a455-0dc8-4359-8a50-843ff1bcfea7"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-05T14:06:19Z"
involvedObject:
  apiVersion: "test.org/v1"
  kind: "TestResource"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "8214310"
  uid: "3329a455-0dc8-4359-8a50-843ff1bcfea7"
lastTimestamp: "2021-07-05T14:06:19Z"
message: "The deployment of TestResource my-namespace/my-app failed due to Database\
  \ preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-c9a4.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "test-controller-pod"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-ource-controller"
type: "Error"
