---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "TestResource"
    EntandoResourceNamespace: "my-namespace"
    TestResource: "my-app"
  name: "my-app-94914557"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "test.org/v1"
    kind: "TestResource"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "34ebc402-8ad3-41d9-9ca2-5a0027843ebd"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-29T11:35:00Z"
involvedObject:
  apiVersion: "test.org/v1"
  kind: "TestResource"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "1619303"
  uid: "34ebc402-8ad3-41d9-9ca2-5a0027843ebd"
lastTimestamp: "2021-06-29T11:35:00Z"
message: "The deployment of TestResource my-namespace/my-app failed due to Database\
  \ preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-2015.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "test-controller-pod"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-ource-controller"
type: "Error"
