---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "TestResource"
    EntandoResourceNamespace: "my-namespace"
    TestResource: "my-app"
  name: "my-app-35714513"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "test.org/v1"
    kind: "TestResource"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "bcf14c56-935f-47fe-a5d7-ed6c5d87d12f"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-14T15:48:03Z"
involvedObject:
  apiVersion: "test.org/v1"
  kind: "TestResource"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "6413329"
  uid: "bcf14c56-935f-47fe-a5d7-ed6c5d87d12f"
lastTimestamp: "2021-06-14T15:48:03Z"
message: "The deployment of TestResource my-namespace/my-app failed due to Database\
  \ preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-3a4d.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
source:
  component: "entando-k8s-ource-controller"
type: "Error"
